services:
  kozmoai:
    image: digitranslab/kozmoai:1.1.8.dev0 # or another version tag on https://hub.docker.com/r/digitranslab/kozmoai
    pull_policy: always               # set to 'always' when using 'latest' image
    ports:
      - "7860:7860"
    depends_on:
      - postgres
    environment:
      - KOZMOAI_DATABASE_URL=postgresql://kozmoai:kozmoai@postgres:5432/kozmoai
      # This variable defines where the logs, file storage, monitor data and secret keys are stored.
      - KOZMOAI_CONFIG_DIR=app/kozmoai
    volumes:
      - kozmoai-data:/app/kozmoai

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: kozmoai
      POSTGRES_PASSWORD: kozmoai
      POSTGRES_DB: kozmoai
    ports:
      - "5432:5432"
    volumes:
      - kozmoai-postgres:/var/lib/postgresql/data

volumes:
  kozmoai-postgres:
  kozmoai-data:
